---
#
# Create Distributed deployment
#
- name: Create Distributed Deployment
  hosts: ise_deployment
  vars:
    ise_username: "{{ lookup('env','ise_username') }}"
    ise_password: "{{ lookup('env','ise_password') }}"
    ise_verify:   "{{ lookup('env','ise_verify') }}"
    ise_login: &ise_login
      ise_hostname: "{{ inventory_hostname }}"
      ise_username: "{{ ise_username }}"
      ise_password: "{{ ise_password }}"
      ise_verify:   "{{ ise_verify }}"
  gather_facts: no
  tasks:

# Check secondary node status

  - name: Check if all secondary nodes are in STANDALONE state
    cisco.ise.personas_check_standalone:
      name: "{{ item.name }}"
      ip: "{{ item.ip }}"
      username: "{{ ise_username }}"
      password: "{{ ise_password }}"
      ise_verify: "{{ ise_verify }}"
    loop:
      - name: ise-2.demo.local
        ip: 10.1.100.22
      - name: ise-cloud.demo.local
        ip: 10.0.1.23


  - name: Export trusted certificates into primary node
    cisco.ise.personas_export_certs:
      primary_ip: 10.1.100.21
      primary_username: "{{ ise_username }}"
      primary_password: "{{ ise_password }}"
      name: "{{ item.name }}"
      ip: "{{ item.ip }}"
      hostname: "{{ item.hostname }}"
      username: "{{ ise_username }}"
      password: "{{ ise_password }}"
      ise_verify: "{{ ise_verify }}"
    loop:
      - name: ise-2.demo.local
        ip: 10.1.100.22
        hostname: ise-2.demo.local
      - name: ise-cloud.demo.local
        ip: 10.0.1.23
        hostname: ise-cloud.demo.local


  - name: Promote primary node from standalone
    cisco.ise.personas_promote_primary:
      ip: 10.1.100.21
      hostname: ise-1.demo.local
      username: "{{ ise_username }}"
      password: "{{ ise_password }}"
      ise_verify: "{{ ise_verify }}"
      roles:
        - PPAN
        - MNT-ACTIVE
        - PDP

  - name: Wait for primary node to convert from standalone to primary 
    pause:
      minutes: 1

  - name: Join secondary nodes to the deployment
    cisco.ise.personas_update_roles:
      primary_ip: 10.1.100.21
      primary_username: "{{ ise_username }}"
      primary_password: "{{ ise_password }}"
      ise_verify: "{{ ise_verify }}"
      name: "{{ item.name }}"
      local_ip: "{{ item.local_ip }}"
      hostname: "{{ item.hostname }}"
      username: "{{ ise_username }}"
      password: "{{ ise_password }}"
      domain: demo.local
      roles: "{{ item.roles }}"
    loop:
      - name: ise-2.demo.local
        local_ip: 10.1.100.22
        hostname: ise-2
        roles:
          - SPAN
          - MNT-STANDBY
      - name: ise-cloud.demo.local
        local_ip: 10.0.1.23
        hostname: ise-cloud
        roles:
          - PDP


  - name: Wait for secondary nodes to finish sync 
    pause:
      minutes: 90


  - name: Delete the PSN role from the primary node
    cisco.ise.personas_promote_primary:
      ip: 10.1.100.21
      hostname: ise-1.demo.local
      username: "{{ ise_username }}"
      password: "{{ ise_password }}"
      ise_verify: "{{ ise_verify }}"
      roles:
        - PPAN
        - MNT-ACTIVE
